name: Prepare Production Release

on:
    workflow_dispatch:

jobs:
    build:
      name: Prepare
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Create a tag
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            VERSION: 'v0.0.1'
          run: |
            git tag "$VERSION"
            git push origin "$VERSION"

        - name: Deploy
          run: |
            mkdir -p dist
            date > dist/info.txt
            cat dist/info.txt
            zip release.zip dist/*
            
        - name: Release
          env:
              GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              VERSION: 'v0.0.1'
          run: |
              curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $GH_TOKEN" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/ladisalves/fastify-rest-test/releases \
              -d "{\"tag_name\":\"$VERSION\",\"target_commitish\":\"master\",\"name\":\"$VERSION\",\"body\":\"Release of $VERSION\",\"draft\":false,\"prerelease\":false,\"generate_release_notes\":false}"            
