name: Prepare Production Release

on:
    workflow_dispatch:

jobs:
    build:
      name: Prepare
      runs-on: ubuntu-latest
      steps:
            - name: Deploy
              run: |
                mkdir -p dist
                date > dist/info.txt
                cat dist/info.txt
            
            - name: Release
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  VERSION='v0.0.1' curl -L \
                  -X POST \
                  -H "Accept: application/vnd.github+json" \
                  -H "Authorization: Bearer $GH_TOKEN" \
                  -H "X-GitHub-Api-Version: 2022-11-28" \
                  https://api.github.com/repos/ladisalves/fastify-rest-test/releases \
                  -d "{\"tag_name\":\"$VERSION\",\"target_commitish\":\"master\",\"name\":\"$VERSION\",\"body\":\"Release of $VERSION\",\"draft\":false,\"prerelease\":false,\"generate_release_notes\":false}"


            
